name: bls_signatures_ffi
description: Flutter plugin for Chia's BLS-Signatures.
version: 0.1.0
homepage: https://github.com/Chia-Network/bls-signatures

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.9
  ffigen: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  very_good_analysis: ^2.4.0

ffigen:
  name: BLSSignatureBindings
  output: "lib/src/blschia.h.dart"
  headers:
    entry-points:
      - "ios/bls/blschia.h"
      - "ios/bls/elements.h"
      - "ios/bls/privatekey.h"
      - "ios/bls/schemes.h"

flutter:
  plugin:
    platforms:
      android:
        package: net.chia.bls_signatures_ffi
        pluginClass: BlsSignaturesFfiPlugin
      ios:
        pluginClass: BlsSignaturesFfiPlugin
