name: bls_signatures_ffi_example
description: Demonstrates how to use the bls_signatures_ffi plugin.
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bls_signatures_ffi:
    path: ../
  convert: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
